/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export type JsAhoCorasick = AhoCorasick
export class AhoCorasick {
  constructor(patterns: Array<string>)
  search(query: string): Array<[number, number, number]>
}
